### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by esakowski** [alabianca/xml-to-json#2]
Any idea why this may be happening?  Web server drops after making a request. 

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at XMLtoJSONstream.Writable.write (_stream_writable.js:287:5)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:130:22)
    at Socket.socketOnData (_http_client.js:440:20)

**Comment by alabianca** [comment]
@esakowski  Can you provide code for me to try and recreate? This error is thrown if you try to write into the stream when the stream has ended. 

```javascript
readable.on('data', function(data) { 
    stream.write(data); //the xmlToJsonStream
    stream.end();
});
```

The above would throw the error if the 'data' event is emitted more than once. This would attempt to write to a closed stream.
